# Generated by Django 3.2.2 on 2021-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
